PROGRAM SUMARRAY
INTEGER NUMS(5)
INTEGER I, SOMA
SOMA = 0
PRINT *, 'Enter 5 integers:'
DO 30 I = 1, 5
READ *, NUMS(I)
SOMA = SOMA + NUMS(I)
30 CONTINUE
PRINT *, 'The sum of the numbers is: ', SOMA
END